sudo: required
dist: zesty
language: c

matrix:
  include:
    # works on Precise and Trusty
    - compiler: gcc
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - COMPILER="CC=gcc-6"

before_install:
  - eval "${COMPILER}"

script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_CC_COMPILER=$COMPILER .. && make
