sudo: required
dist: precise
language: c

matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env:
         - COMPILER="CC=gcc-4.9 && CXX=g++-4.9"

    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
         - COMPILER="CC=gcc-5 && CXX=g++-5"
    # works on Precise and Trusty
    - compiler: gcc
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - COMPILER="CC=gcc-6 && CXX=g++-6"

before_install:
  - eval "${COMPILER}"

script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_CC_COMPILER=$COMPILER .. && make
  - ./uBase
